name: docker-sync-to-aliyun

on:
  push:
  workflow_dispatch: 

jobs:
  images:
    name: 'publish-docker-action:latest'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - busybox:1.31.1
          - bitnami/apache-exporter:0.11.0-debian-11-r73
          - bitnami/wordpress:5.9.2-debian-10-r26
          - bitnami/wordpress:6.1.1-debian-11-r15
          - csiplugin/snapshot-controller:v4.0.0
          - k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
          - k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0
          - k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
          - k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.2
          - k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
          - k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
          - k8s.gcr.io/sig-storage/hostpathplugin:v1.7.3
          - k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          - kubeedge/cloudcore:v1.9.2
          - kubeedge/csidriver:v1.1.0
          - kubeedge/csidriver:v1.9.2
          - kubesphere/edgeservice:v0.2.0
          - kubesphere/kube-rbac-proxy:v0.8.0
          - kubesphere/kube-rbac-proxy:v0.11.0
          - kubesphere/notification-manager-operator:v1.4.0
          - kubesphere/kubectl:v1.22.0
          - kubesphere/kube-state-metrics:v2.5.0
          - kubesphere/ks-installer:v3.3.1
          - kubesphere/ks-console:v3.3.1
          - kubesphere/ks-controller-manager:v3.3.1
          - kubesphere/ks-apiserver:v3.3.1
          - kubesphere/openelb:v0.4.4
          - kubesphere/prometheus-config-reloader:v0.55.1
          - kubesphere/prometheus-operator:v0.55.1
          - kubespheredev/kube-webhook-certgen:v1.1.1
          - mcr.microsoft.com/k8s/csi/nfs-csi:latest
          - mcr.microsoft.com/k8s/csi/nfs-csi:v3.1.0
          - mirrorgooglecontainers/defaultbackend-amd64:1.4
          - nginx:stable-alpine3.17
          - prom/alertmanager:v0.23.0
          - prom/node-exporter:v1.3.1
          - prom/prometheus:v2.34.0
          - quay.io/k8scsi/csi-attacher:v1.1.1
          - quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          - quay.io/k8scsi/csi-provisioner:v1.2.1
          - quay.io/k8scsi/hostpathplugin:v1.1.0

    steps:
    - name: Pull image from Docker Hub
      run: docker pull ${{ matrix.image }}
    - name: Tag image
      id: tag-image
      run: |
        after_image=`echo ${{ matrix.image }} | awk -F "/" '{print $NF}'`  
        docker tag ${{ matrix.image }} registry.cn-hangzhou.aliyuncs.com/hz-test-1/$after_image
        echo ::set-output name=AFTER_IMAGE::$(echo $after_image)
    - name: Login to Aliyun registry
      uses: azure/docker-login@v1
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}  
    - name: Push image to Aliyun
      run: docker push registry.cn-hangzhou.aliyuncs.com/hz-test-1/${{ steps.tag-image.outputs.AFTER_IMAGE }}
