name: docker-sync-to-aliyun

on:
  push:
  workflow_dispatch: 

jobs:
  images:
    name: 'publish-docker-action:latest'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - aledbf/kube-keepalived-vip:0.35
          - alpine:3.15
          - alpine:3.18
          - alpine:3.20
          - busybox:1.31.1
          - bitnami/apache-exporter:0.11.0-debian-11-r73
          - bitnami/influxdb:2.7.10-debian-12-r5
          - bitnami/os-shell:12-debian-12-r30
          - bitnami/postgresql:14.5.0-debian-11-r35
          - bitnami/postgresql:16.0.0-debian-11-r3
          - bitnami/redis:7.2.1-debian-11-r0
          - bitnami/wordpress:5.9.2-debian-10-r26
          - bitnami/wordpress:6.1.1-debian-11-r15
          - calico/cni:v3.23.2
          - calico/kube-controllers:v3.23.2
          - calico/node:v3.23.2
          - csiplugin/snapshot-controller:v4.0.0
          - dn11exp/proxy-miner-exp:1.0.0a10
          - dn11exp/proxy-miner-exp:1.0.0a18
          - dn11exp/proxy-miner-exp:1.0.0a20
          - dn11exp/proxy-miner-exp:1.0.0a22
          - dn11exp/proxy-miner-exp:1.0.0a23
          - dn11exp/proxy-miner-exp:1.0.0a24
          - dn11exp/proxy-miner-exp:1.0.0a27
          - dolibarr/dolibarr:21.0.1
          - feiyu563/prometheus-alert:v4.9
          - gcr.io/k8s-prow/clonerefs:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/crier:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/deck:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/entrypoint:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/ghproxy:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/hook:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/horologium:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/initupload:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/prow-controller-manager:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/sidecar:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/sinker:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/status-reconciler:v20240723-dbbd2d86b
          - gcr.io/k8s-prow/tide:v20240723-dbbd2d86b
          - gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0
          - ghcr.io/05sec/kubeifce:1.0.0a26
          - ghcr.io/05sec/kubeifce:1.0.0a27
          - ghcr.io/actions/gha-runner-scale-set-controller:0.9.2
          - ghcr.io/actions/gha-runner-scale-set-controller:0.9.3
          - ghcr.io/actions/gha-runner-scale-set-controller:0.10.0
          - ghcr.io/actions/gha-runner-scale-set-controller:0.10.1
          - ghcr.io/actions/gha-runner-scale-set-controller:0.11.0
          - ghcr.io/falcondev-oss/github-actions-cache-server:2.1.8
          - ghcr.io/falcondev-oss/github-actions-cache-server:3.1.0
          - ghcr.io/falcondev-oss/github-actions-cache-server:4.0.0
          - ghcr.io/falcondev-oss/github-actions-cache-server:4.0.1
          - ghcr.io/falcondev-oss/github-actions-cache-server:4.0.2
          - ghcr.io/falcondev-oss/github-actions-cache-server:4.0.3
          - ghcr.io/falcondev-oss/github-actions-cache-server:5.0.0
          - ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
          - goharbor/harbor-core:v2.13.0
          - goharbor/harbor-exporter:v2.13.0
          - goharbor/harbor-jobservice:v2.13.0
          - goharbor/harbor-portal:v2.13.0
          - goharbor/harbor-registryctl:v2.13.0
          - goharbor/nginx-photon:v2.13.0
          - goharbor/registry-photon:v2.13.0
          - golang:1.20
          - gotafire/kube-rbac-proxy:v0.13.0
          - gotafire/kube-state-metrics:v2.3.0
          - gotafire/node-exporter:v1.3.1
          - grafana/grafana:8.5.14
          - imroc/cert-manager-webhook-dnspod:1.5.2
          - jetbrainsinfra/jq
          - jimmidyson/configmap-reload:v0.3.0
          - k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
          - k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0
          - k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
          - k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.6.2
          - k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
          - k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
          - k8s.gcr.io/sig-storage/hostpathplugin:v1.7.3
          - k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          - kubeedge/cloudcore:v1.9.2
          - kubeedge/cloudcore:v1.15.2
          - kubeedge/cloudcore:v1.17.0
          - kubeedge/cloudcore:v1.17.5
          - kubeedge/cloudcore:v1.18.3
          - kubeedge/cloudcore:v1.19.2
          - kubeedge/csidriver:v1.1.0
          - kubeedge/csidriver:v1.9.2
          - kubeedge/edgemesh-agent:v1.17.0
          - kubeedge/installation-package:v1.15.2
          - kubeedge/installation-package:v1.17.0
          - kubeedge/installation-package:v1.17.5
          - kubeedge/iptables-manager:v1.15.2
          - kubeedge/iptables-manager:v1.17.0
          - kubeedge/iptables-manager:v1.17.5
          - kubesphere/edgeservice:v0.2.0
          - kubesphere/kube-rbac-proxy:v0.8.0
          - kubesphere/kube-rbac-proxy:v0.11.0
          - kubesphere/notification-manager-operator:v1.4.0
          - kubesphere/kubectl:v1.22.0
          - kubesphere/kube-state-metrics:v2.5.0
          - kubesphere/ks-installer:v3.3.1
          - kubesphere/ks-console:v3.3.1
          - kubesphere/ks-controller-manager:v3.3.1
          - kubesphere/ks-apiserver:v3.3.1
          - kubesphere/openelb:v0.4.4
          - kubesphere/prometheus-config-reloader:v0.55.1
          - kubesphere/prometheus-operator:v0.55.1
          - kubespheredev/kube-webhook-certgen:v1.1.1
          - kubespheredev/metrics-server:v0.4.1
          - liangjw/kube-webhook-certgen:v1.1.1
          - longhornio/longhorn-engine:v1.7.3
          - longhornio/longhorn-manager:v1.7.3
          - longhornio/longhorn-ui:v1.7.3
          - longhornio/longhorn-instance-manager:v1.7.3
          - longhornio/longhorn-share-manager:v1.7.3
          - longhornio/backing-image-manager:v1.7.3
          - longhornio/support-bundle-kit:v0.0.51
          - longhornio/csi-attacher:v4.8.0
          - longhornio/csi-provisioner:v4.0.1-20250204
          - longhornio/csi-node-driver-registrar:v2.13.0
          - longhornio/csi-resizer:v1.13.1
          - longhornio/csi-snapshotter:v7.0.2-20250204
          - longhornio/livenessprobe:v2.15.0
          - mcr.microsoft.com/k8s/csi/nfs-csi:latest
          - mcr.microsoft.com/k8s/csi/nfs-csi:v3.1.0
          - minio/minio:latest
          - mirrorgooglecontainers/defaultbackend-amd64:1.4
          - mongo:5.0.6
          - mysql:5.7
          - n8nio/n8n:1.58.2
          - nginx:stable-alpine3.17
          - ollama/ollama:0.5.13
          - openebs/node-disk-manager:2.1.0
          - openebs/node-disk-operator:2.1.0
          - openebs/provisioner-localpv:3.5.0
          - openebs/linux-utils:3.5.0
          - postgres:14-alpine
          - postgres:15-alpine
          - postgres:16-alpine
          - postgres:17-alpine
          - projecthami/hami:v2.5.0
          - prom/alertmanager:v0.23.0
          - prom/node-exporter:v1.3.1
          - prom/prometheus:v2.34.0
          - quay.io/argoproj/argocd:v2.8.20
          - quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
          - quay.io/jetstack/cert-manager-acmesolver:v1.12.17
          - quay.io/jetstack/cert-manager-acmesolver:v1.16.5
          - quay.io/jetstack/cert-manager-acmesolver:v1.17.2
          - quay.io/jetstack/cert-manager-cainjector:v1.12.17
          - quay.io/jetstack/cert-manager-cainjector:v1.16.5
          - quay.io/jetstack/cert-manager-cainjector:v1.17.2
          - quay.io/jetstack/cert-manager-controller:v1.12.17
          - quay.io/jetstack/cert-manager-controller:v1.16.5
          - quay.io/jetstack/cert-manager-controller:v1.17.2
          - quay.io/jetstack/cert-manager-startupapicheck:v1.12.17
          - quay.io/jetstack/cert-manager-startupapicheck:v1.16.5
          - quay.io/jetstack/cert-manager-startupapicheck:v1.17.2
          - quay.io/jetstack/cert-manager-webhook:v1.12.17
          - quay.io/jetstack/cert-manager-webhook:v1.16.5
          - quay.io/jetstack/cert-manager-webhook:v1.17.2
          - quay.io/kubevirt/macvtap-cni:v0.12.2
          - quay.io/k8scsi/csi-attacher:v1.1.1
          - quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          - quay.io/k8scsi/csi-provisioner:v1.2.1
          - quay.io/k8scsi/hostpathplugin:v1.1.0
          - redis:7
          - redis:7-alpine
          - registry.k8s.io/dns/k8s-dns-node-cache:1.22.20
          - registry.k8s.io/ingress-nginx/controller:v1.10.0
          - registry.k8s.io/ingress-nginx/controller:v1.10.1
          - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.0
          - registry.k8s.io/pause:3.9
          - registry.suse.com/bci/bci-base:15.5
          - tile38/tile38:1.34.1
          - ubuntu:22.04
          - victoriametrics/operator:v0.25.1
          - victoriametrics/victoria-metrics:v1.77.1
          - victoriametrics/vmagent:v1.77.1
          - victoriametrics/vmalert:v1.76.0
          - vllm/vllm-openai:v0.7.3
          - vulhub/redis:5.0.7
          - wardsco/sleep:latest
          - yisier1/nps:v0.26.19

    steps:
    - name: Pull image from Docker Hub
      run: docker pull ${{ matrix.image }}
    - name: Tag image
      id: tag-image
      run: |
        after_image=`echo ${{ matrix.image }} | awk -F "/" '{print $NF}'`  
        docker tag ${{ matrix.image }} registry.cn-hangzhou.aliyuncs.com/hz-test-1/$after_image
        echo ::set-output name=AFTER_IMAGE::$(echo $after_image)
    - name: Login to Aliyun registry
      uses: azure/docker-login@v1
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}  
    - name: Push image to Aliyun
      run: docker push registry.cn-hangzhou.aliyuncs.com/hz-test-1/${{ steps.tag-image.outputs.AFTER_IMAGE }}
